// <auto-generated />
using System;
using BTLWNCao.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLWNCao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405095358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTLWNCao.Models.CongTy", b =>
                {
                    b.Property<int>("MaCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongTy"));

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThongTinCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCongTy");

                    b.ToTable("CongTys");
                });

            modelBuilder.Entity("BTLWNCao.Models.DuAn", b =>
                {
                    b.Property<int>("MaDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuAn"));

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<int>("MaUserCongTy")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungDuAn")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDuAn");

                    b.HasIndex("MaCongTy");

                    b.HasIndex("MaUserCongTy");

                    b.ToTable("DuAns");
                });

            modelBuilder.Entity("BTLWNCao.Models.NhomChat", b =>
                {
                    b.Property<int>("MaNhomChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomChat"));

                    b.Property<int>("MaUserCongTy")
                        .HasColumnType("int");

                    b.Property<string>("TenNhomChat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhomChat");

                    b.HasIndex("MaUserCongTy");

                    b.ToTable("NhomChats");
                });

            modelBuilder.Entity("BTLWNCao.Models.PhanCongCongViec", b =>
                {
                    b.Property<int>("MaCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongViec"));

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileTaiLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int");

                    b.Property<int>("MaUserCongTy")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaCongViec");

                    b.HasIndex("MaCongTy");

                    b.HasIndex("MaDuAn");

                    b.HasIndex("MaUserCongTy");

                    b.ToTable("PhanCongCongViecs");
                });

            modelBuilder.Entity("BTLWNCao.Models.TinNhan", b =>
                {
                    b.Property<int>("MaChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChat"));

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileTaiLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNhomChat")
                        .HasColumnType("int");

                    b.Property<int>("MaUserNhomChat")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChat");

                    b.HasIndex("MaNhomChat");

                    b.HasIndex("MaUserNhomChat");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("BTLWNCao.Models.User", b =>
                {
                    b.Property<int>("MaUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BTLWNCao.Models.UserCongTy", b =>
                {
                    b.Property<int>("MaUserCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUserCongTy"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<int>("MaUser")
                        .HasColumnType("int");

                    b.HasKey("MaUserCongTy");

                    b.HasIndex("MaCongTy");

                    b.HasIndex("MaUser");

                    b.ToTable("UserCongTys");
                });

            modelBuilder.Entity("BTLWNCao.Models.UserNhomChat", b =>
                {
                    b.Property<int>("MaUserNhomChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUserNhomChat"));

                    b.Property<int>("MaNhomChat")
                        .HasColumnType("int");

                    b.Property<int>("MaUserCongTy")
                        .HasColumnType("int");

                    b.HasKey("MaUserNhomChat");

                    b.HasIndex("MaNhomChat");

                    b.HasIndex("MaUserCongTy");

                    b.ToTable("UserNhomChats");
                });

            modelBuilder.Entity("BTLWNCao.Models.DuAn", b =>
                {
                    b.HasOne("BTLWNCao.Models.CongTy", "CongTy")
                        .WithMany("DuAns")
                        .HasForeignKey("MaCongTy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTLWNCao.Models.UserCongTy", "UserCongTy")
                        .WithMany("DuAns")
                        .HasForeignKey("MaUserCongTy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongTy");

                    b.Navigation("UserCongTy");
                });

            modelBuilder.Entity("BTLWNCao.Models.NhomChat", b =>
                {
                    b.HasOne("BTLWNCao.Models.UserCongTy", "UserCongTy")
                        .WithMany("NhomChats")
                        .HasForeignKey("MaUserCongTy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserCongTy");
                });

            modelBuilder.Entity("BTLWNCao.Models.PhanCongCongViec", b =>
                {
                    b.HasOne("BTLWNCao.Models.CongTy", "CongTy")
                        .WithMany()
                        .HasForeignKey("MaCongTy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTLWNCao.Models.DuAn", "DuAn")
                        .WithMany("PhanCongCongViecs")
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTLWNCao.Models.UserCongTy", "UserCongTy")
                        .WithMany("PhanCongCongViecs")
                        .HasForeignKey("MaUserCongTy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongTy");

                    b.Navigation("DuAn");

                    b.Navigation("UserCongTy");
                });

            modelBuilder.Entity("BTLWNCao.Models.TinNhan", b =>
                {
                    b.HasOne("BTLWNCao.Models.NhomChat", "NhomChat")
                        .WithMany("TinNhans")
                        .HasForeignKey("MaNhomChat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTLWNCao.Models.UserNhomChat", "UserNhomChat")
                        .WithMany("TinNhans")
                        .HasForeignKey("MaUserNhomChat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomChat");

                    b.Navigation("UserNhomChat");
                });

            modelBuilder.Entity("BTLWNCao.Models.UserCongTy", b =>
                {
                    b.HasOne("BTLWNCao.Models.CongTy", "CongTy")
                        .WithMany("UserCongTys")
                        .HasForeignKey("MaCongTy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTLWNCao.Models.User", "User")
                        .WithMany("UserCongTys")
                        .HasForeignKey("MaUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongTy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BTLWNCao.Models.UserNhomChat", b =>
                {
                    b.HasOne("BTLWNCao.Models.NhomChat", "NhomChat")
                        .WithMany("UserNhomChats")
                        .HasForeignKey("MaNhomChat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTLWNCao.Models.UserCongTy", "UserCongTy")
                        .WithMany("UserNhomChats")
                        .HasForeignKey("MaUserCongTy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomChat");

                    b.Navigation("UserCongTy");
                });

            modelBuilder.Entity("BTLWNCao.Models.CongTy", b =>
                {
                    b.Navigation("DuAns");

                    b.Navigation("UserCongTys");
                });

            modelBuilder.Entity("BTLWNCao.Models.DuAn", b =>
                {
                    b.Navigation("PhanCongCongViecs");
                });

            modelBuilder.Entity("BTLWNCao.Models.NhomChat", b =>
                {
                    b.Navigation("TinNhans");

                    b.Navigation("UserNhomChats");
                });

            modelBuilder.Entity("BTLWNCao.Models.User", b =>
                {
                    b.Navigation("UserCongTys");
                });

            modelBuilder.Entity("BTLWNCao.Models.UserCongTy", b =>
                {
                    b.Navigation("DuAns");

                    b.Navigation("NhomChats");

                    b.Navigation("PhanCongCongViecs");

                    b.Navigation("UserNhomChats");
                });

            modelBuilder.Entity("BTLWNCao.Models.UserNhomChat", b =>
                {
                    b.Navigation("TinNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
